import { useContext } from 'react'
import { AuthContext} from '@/context/Autcontext'
import { Inter } from 'next/font/google'
import './globals.css'
import { AuthContext } from './context/AuthContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Demo with Context',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
